const tintColorLight = '#0ea5a0';
const tintColorDark = '#2dd4bf';

export default {
  light: {
    text: '#1a1a1a',
    textSecondary: '#8e8e93',
    background: '#f5f5f7',
    surface: '#ffffff',
    surfaceSecondary: '#f2f2f7',
    surfaceDark: '#1c1c1e',
    tint: tintColorLight,
    tabIconDefault: '#c7c7cc',
    tabIconSelected: tintColorLight,
    border: '#e5e5ea',
    success: '#30d158',
    warning: '#ff9f0a',
    error: '#ff453a',
    pomodoroWork: '#0ea5a0',
    pomodoroShortBreak: '#30d158',
    pomodoroLongBreak: '#007aff',
    progressTrack: '#e5e5ea',
    buttonPrimary: '#0ea5a0',
    buttonSecondary: '#f2f2f7',
    card: '#ffffff',
    cardDark: '#1c1c1e',
  },
  dark: {
    text: '#f5f5f7',
    textSecondary: '#8e8e93',
    background: '#000000',
    surface: '#1c1c1e',
    surfaceSecondary: '#2c2c2e',
    surfaceDark: '#1c1c1e',
    tint: tintColorDark,
    tabIconDefault: '#636366',
    tabIconSelected: tintColorDark,
    border: '#38383a',
    success: '#30d158',
    warning: '#ff9f0a',
    error: '#ff453a',
    pomodoroWork: '#2dd4bf',
    pomodoroShortBreak: '#30d158',
    pomodoroLongBreak: '#64d2ff',
    progressTrack: '#38383a',
    buttonPrimary: '#2dd4bf',
    buttonSecondary: '#2c2c2e',
    card: '#1c1c1e',
    cardDark: '#2c2c2e',
  },
};
